name: Ci Pipeline  # Name of the pipeline


on:
  push:           # only at the time of push
    branches:
      - main     # Only for the main Branch

jobs:
  CICD_Pipeline_Test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # upload code on github
